### ISSUE TITLE
Improved Secret Management

### ISSUE THREAD

**Issue by lbeckman314** [ACED-IDP/gen3-helm#42]
## Tasks for Secret Management
> Test the following on the local deployment, then deploy following the [development → staging → production pipeline](https://github.com/ACED-IDP/gen3-helm/wiki/3.-Code-Management#branching-strategy)

- [ ] Collect all credentials/secrets from current values files into one "Secret" yaml file (leaving "sanitized" values files without any secrets)
- [ ] Upload the yaml file for each deployment containing credentials/secrets
- [ ] Write script to run before each deployment to pull the secrets and populate the sanitized values files
- [ ] Add and configure [git-secrets](https://github.com/awslabs/git-secrets)
- [ ] Check in the sanitized values files into version control
